#!/bin/bash

# Shell script to count the number of words and white spaces in a phrase

echo "Please type a phrase:"
read phrase

# Count the number of words using the 'wc' command and subtract 1 to exclude the newline character
word_count=$(echo $phrase | wc -w)

# Count the number of white spaces using the 'grep' command and 'tr' command
space_count=$(echo $phrase | grep -o ' ' | tr -d -c ' ' | wc -c)

echo "The number of words is $word_count"
echo "The number of white spaces is $space_count"
